//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "packet_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub packet_id: i32,
    #[sea_orm(column_type = "Text")]
    pub packet_type: String,
    #[sea_orm(column_type = "Text")]
    pub event_name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub des_json: Json,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
